# -*- coding: utf-8 -*-
"""Image processing

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zwnaztYINixbo6Hh7XtieKCdxu8bcYYX
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

img = cv2.imread("/content/drive/MyDrive/INTERNSHIP /laptop.jpg")
print(img)



print(type(img))

cv2_imshow(img)

cv2.waitKey(0)
height, width = img.shape[0:2]
img.shape[0:2]
print(img.shape[0:2])
rotation_matrix = cv2.getRotationMatrix2D((width/2, height/2), 90, .5)
rotated_image = cv2.warpAffine(img, rotation_matrix, (width, height))

cv2_imshow(rotated_image)
cv2.waitKey(0)

start_row = int(height*.15)
end_row = int(height*.7)
start_col = int(width*.15)
end_col = int(width*.85)
cropped_image = img[start_row:end_row, start_col:end_col]

cv2_imshow(img)
cv2_imshow(cropped_image)
cv2.waitKey(0)



new_img = cv2.resize(img, (0,0), fx=0.75, fy=0.75)

cv2_imshow(new_img)
cv2.waitKey(0)

newImg = cv2.resize(img, (550, 350))
cv2_imshow(newImg)
cv2.waitKey(0)

a=1.5
b=50
new_img = a * img + b
cv2_imshow(img)
cv2.waitKey(0)

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
img = cv2.imread("/content/drive/MyDrive/INTERNSHIP /laptop.jpg")
contrast_img = cv2.addWeighted(img, 2.5, np.zeros_like(img), 0, 0)
cv2_imshow(img)
cv2_imshow(contrast_img)

from google.colab.patches import cv2_imshow
import cv2

img = cv2.imread("/content/drive/MyDrive/INTERNSHIP /laptop.jpg")
blur_image = cv2.GaussianBlur(img, (7,7), 0)

cv2_imshow(img)
cv2_imshow(blur_image)
cv2.waitKey(0)

from google.colab.patches import cv2_imshow
import cv2

img = cv2.imread("/content/drive/MyDrive/INTERNSHIP /laptop.jpg")
edge_img = cv2.Canny(img, 100, 200)

cv2_imshow(img)
cv2_imshow(edge_img)
cv2.waitKey(0)

from google.colab.patches import cv2_imshow
import cv2

img = cv2.imread("/content/drive/MyDrive/INTERNSHIP /laptop.jpg")
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

cv2_imshow(img)  # Display the original image
cv2_imshow(gray_img)  # Display the grayscale image

cv2.waitKey(0)

from google.colab.patches import cv2_imshow
import cv2

img = cv2.imread("/content/drive/MyDrive/INTERNSHIP /laptop.jpg")
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
moment = cv2.moments(gray_img)
X = int(moment["m10"] / moment["m00"])
Y = int(moment["m01"] / moment["m00"])
cv2.circle(img, (X, Y), 15, (205, 114, 101), 1)
cv2_imshow(img)
cv2.waitKey(0)